[build]
# Sadece Aycan İnşaat projesini kur ve derle
command = "npm install --prefix apps/craftops/aycaninsaat && npm run build --prefix apps/craftops/aycaninsaat"
  publish = "dist"

# --- YENİ EKLENEN KURAL: STOK DEMO ---
[[redirects]]
  from = "/craftops/stokdemo/*"
  to = "/craftops/stokdemo/index.html"
  status = 200

  [[redirects]]
  from = "/craftops/finansdemo/*"
  to = "/craftops/finansdemo/index.html"
  status = 200

# MEVCUT KURALLAR
[[redirects]]
  from = "/craftops/editioncoffeeroastery/*"
  to = "/craftops/editioncoffeeroastery/index.html"
  status = 200

[[redirects]]
  from = "/craftops/aycaninsaat/*"
  to = "/craftops/aycaninsaat/index.html"
  status = 200

# ANA UYGULAMA (En Sonda Olmalı)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200